/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: fbadcb116ab9dc8ce5f745467039a396)
interface __BaseEnv_Env {
	AI: Ai;
	SERVICE_NAME: "duolingo-avator-creator";
	SERVICE_VERSION: "0.3.0";
	AI_TEXT_MODEL: "@cf/meta/llama-3.1-8b-instruct-fast";
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
